version: "3.1"

services:
  db:
    image: postgres
    container_name: ufu_dev
    environment:
      POSTGRES_PASSWORD: banco
      POSTGRES_DB: ufu_dev
    ports:
      - "5432:5432"

volumes:
  pgdata: